using System.Text.Json.Serialization;
using Tomur.Api;
using Tomur.Api.Models;
using Tomur.Api.OpenAI;
using Tomur.Api.Ollama;
using Tomur.Agents;
using Tomur.Config;
using Tomur.Conversations;
using Tomur.Hardware;
using Tomur.Multimodal;
using Tomur.Native;
using Tomur.Runtime;
using Tomur.Models;
using Tomur.Services;
using Tomur.Storage;

namespace Tomur.Serialization;

[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(RootResponse))]
[JsonSerializable(typeof(VersionResponse))]
[JsonSerializable(typeof(OpenAiModelListResponse))]
[JsonSerializable(typeof(OpenAiModelResponse))]
[JsonSerializable(typeof(OpenAiChatCompletionRequest))]
[JsonSerializable(typeof(OpenAiChatMessage))]
[JsonSerializable(typeof(OpenAiChatCompletionResponse))]
[JsonSerializable(typeof(OpenAiChatCompletionChoice))]
[JsonSerializable(typeof(OpenAiChatCompletionMessage))]
[JsonSerializable(typeof(OpenAiChatCompletionChunk))]
[JsonSerializable(typeof(OpenAiChatCompletionChunkChoice))]
[JsonSerializable(typeof(OpenAiChatCompletionDelta))]
[JsonSerializable(typeof(OpenAiCompletionRequest))]
[JsonSerializable(typeof(OpenAiCompletionResponse))]
[JsonSerializable(typeof(OpenAiCompletionChoice))]
[JsonSerializable(typeof(OpenAiCompletionChunk))]
[JsonSerializable(typeof(OpenAiCompletionChunkChoice))]
[JsonSerializable(typeof(OpenAiUsage))]
[JsonSerializable(typeof(OpenAiEmbeddingRequest))]
[JsonSerializable(typeof(OpenAiEmbeddingResponse))]
[JsonSerializable(typeof(OpenAiEmbeddingData))]
[JsonSerializable(typeof(OpenAiImageGenerationRequest))]
[JsonSerializable(typeof(OpenAiImageGenerationResponse))]
[JsonSerializable(typeof(OpenAiImageGenerationData))]
[JsonSerializable(typeof(OpenAiAudioSpeechRequest))]
[JsonSerializable(typeof(OpenAiAudioTranscriptionResponse))]
[JsonSerializable(typeof(OpenAiErrorResponse))]
[JsonSerializable(typeof(OpenAiError))]
[JsonSerializable(typeof(OllamaChatRequest))]
[JsonSerializable(typeof(OllamaChatMessage))]
[JsonSerializable(typeof(OllamaGenerateRequest))]
[JsonSerializable(typeof(OllamaGenerateResponse))]
[JsonSerializable(typeof(OllamaChatResponse))]
[JsonSerializable(typeof(OllamaModelListResponse))]
[JsonSerializable(typeof(OllamaModelResponse))]
[JsonSerializable(typeof(OllamaModelDetails))]
[JsonSerializable(typeof(OllamaShowRequest))]
[JsonSerializable(typeof(OllamaShowResponse))]
[JsonSerializable(typeof(OllamaModelInfo))]
[JsonSerializable(typeof(OllamaErrorResponse))]
[JsonSerializable(typeof(MultimodalRuntimeStatus))]
[JsonSerializable(typeof(MultimodalBackendStatus))]
[JsonSerializable(typeof(VisionAnalysisRequest))]
[JsonSerializable(typeof(OcrAnalysisRequest))]
[JsonSerializable(typeof(MultimodalImageInput))]
[JsonSerializable(typeof(MultimodalInputSummary))]
[JsonSerializable(typeof(MultimodalOperationResponse))]
[JsonSerializable(typeof(MultimodalTextResponse))]
[JsonSerializable(typeof(ImageGenerationOptions))]
[JsonSerializable(typeof(ImageGenerationWorkerRequest))]
[JsonSerializable(typeof(ImageGenerationWorkerResponse))]
[JsonSerializable(typeof(RuntimeWorkerError))]
[JsonSerializable(typeof(AgentRuntimeStatus))]
[JsonSerializable(typeof(AgentChatClientStatus))]
[JsonSerializable(typeof(AgentFrameworkStatus))]
[JsonSerializable(typeof(AgentOrchestrationStatus))]
[JsonSerializable(typeof(AgentToolStatus))]
[JsonSerializable(typeof(AgentToolMapResponse))]
[JsonSerializable(typeof(AgentFrameworkToolBindingResponse))]
[JsonSerializable(typeof(AgentFrameworkToolBinding))]
[JsonSerializable(typeof(AgentToolDescriptor))]
[JsonSerializable(typeof(AgentChatRequest))]
[JsonSerializable(typeof(AgentReadOnlyWorkflowRequest))]
[JsonSerializable(typeof(AgentChatMessage))]
[JsonSerializable(typeof(AgentChatToolResult))]
[JsonSerializable(typeof(AgentChatToolRequest))]
[JsonSerializable(typeof(AgentChatResponse))]
[JsonSerializable(typeof(AgentReadOnlyWorkflowResponse))]
[JsonSerializable(typeof(AgentChatToolCall))]
[JsonSerializable(typeof(RuntimeDiagnoseToolResult))]
[JsonSerializable(typeof(AgentToolExecutionResult))]
[JsonSerializable(typeof(AgentToolArtifact))]
[JsonSerializable(typeof(FileSearchToolArguments))]
[JsonSerializable(typeof(FileSearchToolResult))]
[JsonSerializable(typeof(FileIndexSummary))]
[JsonSerializable(typeof(FileSearchMatch))]
[JsonSerializable(typeof(BlockedToolResult))]
[JsonSerializable(typeof(AgentToolInvokeRequest))]
[JsonSerializable(typeof(AgentToolInvokeResponse))]
[JsonSerializable(typeof(AgentToolInvokeAudit))]
[JsonSerializable(typeof(AgentErrorResponse))]
[JsonSerializable(typeof(AgentEventLogRecentResponse))]
[JsonSerializable(typeof(AgentEventLogEntry))]
[JsonSerializable(typeof(AgentTelemetryStatus))]
[JsonSerializable(typeof(AgentTelemetryExporterStatus))]
[JsonSerializable(typeof(AgentTelemetrySpanDescriptor))]
[JsonSerializable(typeof(AgentTelemetryAttributeDescriptor))]
[JsonSerializable(typeof(ConversationListResponse))]
[JsonSerializable(typeof(ConversationDetailResponse))]
[JsonSerializable(typeof(ConversationCreateRequest))]
[JsonSerializable(typeof(ConversationCreateResponse))]
[JsonSerializable(typeof(ConversationAppendMessageRequest))]
[JsonSerializable(typeof(ConversationAppendMessageResponse))]
[JsonSerializable(typeof(ConversationRegisterArtifactRequest))]
[JsonSerializable(typeof(ConversationRegisterArtifactResponse))]
[JsonSerializable(typeof(ConversationAppendDiagnosticRequest))]
[JsonSerializable(typeof(ConversationAppendDiagnosticResponse))]
[JsonSerializable(typeof(ConversationTurnRequest))]
[JsonSerializable(typeof(ConversationTurnResponse))]
[JsonSerializable(typeof(ConversationVoiceTurnRequest))]
[JsonSerializable(typeof(ConversationVoiceTurnResponse))]
[JsonSerializable(typeof(ConversationRecord))]
[JsonSerializable(typeof(ConversationMessageRecord))]
[JsonSerializable(typeof(ConversationArtifactRecord))]
[JsonSerializable(typeof(ConversationDiagnosticRecord))]
[JsonSerializable(typeof(ConversationAttachment))]
[JsonSerializable(typeof(ConversationToolCall))]
[JsonSerializable(typeof(ConversationAttachment[]))]
[JsonSerializable(typeof(ConversationToolCall[]))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(ModelCatalogResponse))]
[JsonSerializable(typeof(ModelHardwareProfileResponse))]
[JsonSerializable(typeof(ModelCatalogPackageResponse))]
[JsonSerializable(typeof(ModelCatalogAssetResponse))]
[JsonSerializable(typeof(ModelCatalogBundleAssetResponse))]
[JsonSerializable(typeof(InstalledModelsResponse))]
[JsonSerializable(typeof(InstalledModelPackageResponse))]
[JsonSerializable(typeof(InstalledModelAssetResponse))]
[JsonSerializable(typeof(VisibleModelResponse))]
[JsonSerializable(typeof(InstallManifest))]
[JsonSerializable(typeof(InstalledModelPackage))]
[JsonSerializable(typeof(InstalledModelAsset))]
[JsonSerializable(typeof(ModelBundleAsset))]
[JsonSerializable(typeof(LocalConfiguration))]
[JsonSerializable(typeof(ServerConfiguration))]
[JsonSerializable(typeof(PathConfiguration))]
[JsonSerializable(typeof(RuntimeConfiguration))]
[JsonSerializable(typeof(ConfigurationState))]
[JsonSerializable(typeof(ServerOptions))]
[JsonSerializable(typeof(RuntimeDiagnostic))]
[JsonSerializable(typeof(AccelerationPlan))]
[JsonSerializable(typeof(AcceleratorDevice))]
[JsonSerializable(typeof(AccelerationBackendStatus))]
[JsonSerializable(typeof(RuntimeStatusResponse))]
[JsonSerializable(typeof(DoctorReport))]
[JsonSerializable(typeof(NativeBundleManifest))]
[JsonSerializable(typeof(NativeBundleComponent))]
[JsonSerializable(typeof(NativeBundleSource))]
[JsonSerializable(typeof(NativeBundleLibrary))]
[JsonSerializable(typeof(NativeBundleVariant))]
[JsonSerializable(typeof(NativeBundleProbeResult))]
[JsonSerializable(typeof(NativeComponentProbeResult))]
[JsonSerializable(typeof(NativeLibraryProbeResult))]
[JsonSerializable(typeof(NativeBundlePrepareResult))]
[JsonSerializable(typeof(NativeBundleFilePrepareResult))]
[JsonSerializable(typeof(NativeLibraryResolution))]
[JsonSerializable(typeof(NativeLibraryLoadResult))]
[JsonSerializable(typeof(SystemSnapshot))]
[JsonSerializable(typeof(DirectoryState))]
[JsonSerializable(typeof(DiskState))]
[JsonSerializable(typeof(ProxyState))]
[JsonSerializable(typeof(PortState))]
[JsonSerializable(typeof(DiagnosticItem))]
[JsonSerializable(typeof(LocalDatabaseState))]
[JsonSerializable(typeof(ApiKeyStoreState))]
[JsonSerializable(typeof(ApiKeyRecord))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
public sealed partial class AppJsonSerializerContext : JsonSerializerContext;
