using System.Text;

namespace Tomur.Providers.Glm;

internal sealed class IncrementalTextDecoder
{
    private const int MaximumStopTokenCount = 1024;
    private const int MaximumStopSequenceCount = 256;
    private const int MaximumStopSequenceLength = 4096;
    private readonly ManagedTokenizer tokenizer;
    private readonly HashSet<int> stopTokenIds;
    private readonly string[] stopSequences;
    private readonly Action<string>? onText;
    private readonly bool skipSpecialTokens;
    private readonly Decoder utf8Decoder = new UTF8Encoding(false, false).GetDecoder();
    private readonly StringBuilder pendingText = new();
    private readonly StringBuilder output = new();
    private bool firstDecodedToken = true;
    private bool completed;

    public IncrementalTextDecoder(
        ManagedTokenizer tokenizer,
        IEnumerable<int> stopTokenIds,
        IEnumerable<string> stopSequences,
        Action<string>? onText = null,
        bool skipSpecialTokens = true)
    {
        ArgumentNullException.ThrowIfNull(tokenizer);
        ArgumentNullException.ThrowIfNull(stopTokenIds);
        ArgumentNullException.ThrowIfNull(stopSequences);
        this.tokenizer = tokenizer;
        this.onText = onText;
        this.skipSpecialTokens = skipSpecialTokens;
        this.stopTokenIds = stopTokenIds.Distinct().ToHashSet();
        if (this.stopTokenIds.Count > MaximumStopTokenCount)
        {
            throw new ArgumentOutOfRangeException(
                nameof(stopTokenIds),
                $"At most {MaximumStopTokenCount} stop token IDs are allowed.");
        }
        if (this.stopTokenIds.Any(tokenId => !tokenizer.ContainsTokenId(tokenId)))
        {
            throw new ArgumentOutOfRangeException(
                nameof(stopTokenIds),
                "Every stop token ID must exist in the tokenizer vocabulary.");
        }

        this.stopSequences = stopSequences
            .Where(static value => !string.IsNullOrEmpty(value))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (this.stopSequences.Length > MaximumStopSequenceCount ||
            this.stopSequences.Any(static value => value.Length > MaximumStopSequenceLength))
        {
            throw new ArgumentOutOfRangeException(
                nameof(stopSequences),
                $"At most {MaximumStopSequenceCount} stop sequences of {MaximumStopSequenceLength} UTF-16 code units are allowed.");
        }
    }

    public bool Stopped { get; private set; }

    public int? StopTokenId { get; private set; }

    public string? StopSequence { get; private set; }

    public string Text => output.ToString();

    public void AppendToken(int tokenId)
    {
        if (completed)
        {
            throw new InvalidOperationException("Incremental decoding has already completed.");
        }

        if (Stopped)
        {
            return;
        }

        if (stopTokenIds.Contains(tokenId))
        {
            FlushUtf8();
            if (!Stopped)
            {
                EmitPending();
                Stopped = true;
                StopTokenId = tokenId;
            }

            completed = true;
            return;
        }

        var bytes = tokenizer.DecodeTokenBytes(tokenId, skipSpecialTokens, firstDecodedToken);
        if (bytes.Length == 0)
        {
            return;
        }

        firstDecodedToken = false;
        DecodeBytes(bytes, flush: false);
    }

    public void Complete()
    {
        if (completed)
        {
            return;
        }

        FlushUtf8();
        if (!Stopped)
        {
            EmitPending();
        }

        completed = true;
    }

    private void FlushUtf8() => DecodeBytes([], flush: true);

    private void DecodeBytes(ReadOnlySpan<byte> bytes, bool flush)
    {
        var maximumCharacters = Math.Max(2, Encoding.UTF8.GetMaxCharCount(bytes.Length));
        var characters = new char[maximumCharacters];
        utf8Decoder.Convert(
            bytes,
            characters,
            flush,
            out var bytesUsed,
            out var charactersUsed,
            out var decoderCompleted);
        if (bytesUsed != bytes.Length || (flush && !decoderCompleted))
        {
            throw new InvalidDataException("Tokenizer UTF-8 decoder could not consume the generated byte sequence.");
        }

        if (charactersUsed > 0)
        {
            FilterStops(new string(characters, 0, charactersUsed));
        }
    }

    private void FilterStops(string value)
    {
        pendingText.Append(value);
        if (stopSequences.Length == 0)
        {
            EmitPending();
            return;
        }

        var pending = pendingText.ToString();
        var stopIndex = -1;
        string? matchedStop = null;
        foreach (var stop in stopSequences)
        {
            var index = pending.IndexOf(stop, StringComparison.Ordinal);
            if (index < 0 ||
                (stopIndex >= 0 && index > stopIndex) ||
                (index == stopIndex && matchedStop is not null && stop.Length <= matchedStop.Length))
            {
                continue;
            }

            stopIndex = index;
            matchedStop = stop;
        }

        if (stopIndex >= 0)
        {
            Emit(pending[..stopIndex]);
            pendingText.Clear();
            Stopped = true;
            StopSequence = matchedStop;
            return;
        }

        var retainedLength = FindRetainedSuffixLength(pending);
        var emittedLength = pending.Length - retainedLength;
        if (emittedLength > 0)
        {
            Emit(pending[..emittedLength]);
            pendingText.Remove(0, emittedLength);
        }
    }

    private int FindRetainedSuffixLength(string pending)
    {
        var retainedLength = 0;
        foreach (var stop in stopSequences)
        {
            var maximum = Math.Min(pending.Length, stop.Length - 1);
            for (var length = maximum; length > retainedLength; length--)
            {
                if (pending.AsSpan(pending.Length - length).SequenceEqual(stop.AsSpan(0, length)))
                {
                    retainedLength = length;
                    break;
                }
            }
        }

        return retainedLength;
    }

    private void EmitPending()
    {
        if (pendingText.Length == 0)
        {
            return;
        }

        Emit(pendingText.ToString());
        pendingText.Clear();
    }

    private void Emit(string value)
    {
        if (value.Length == 0)
        {
            return;
        }

        output.Append(value);
        onText?.Invoke(value);
    }
}
